### ISSUE TITLE
How do your results compare with those of the original implementation?

### ISSUE THREAD

**Issue by cbsudux** [akanimax/pro-gan#1]
Stats will be informative.

**Comment by akanimax** [comment]
Hi @cbsudux,

Sorry. I didn't realize this issue was here. Mainly, users of the package open issues on the package repo itself.
I have recently added the results of the CelebA-HQ experiment on the package repo. The results highly resemble the paper results perceptually. An FID would confirm it. Do check it out. Also, I have added a lot of new features to the package including Conditional Progressive generation using the projection mechanism.

Hope this helps.

Best regards,
@akanimax
